### ISSUE TITLE
exposing UUIDs instead of obfuscating primary key

### ISSUE THREAD

**Issue by dereuromark** [UseMuffin/Obfuscate#15]
I am actually thinking to go more into https://github.com/dereuromark/cakephp-expose if "real obfuscating" is actually the primary goal - for several reasons.

But I guess the "short id" obfuscate stategy can still be useful probably.
Short URL generation or alike.
Just not for obfuscating, as those are not really "secure" and still allow tracking of the primary key data and basic ordering (including then count of records per time-frame).

Should this be a note maybe in the Readme?

**Comment by jadb** [comment]
What I like about this plugin vs. expose is the ability to control the obfuscation method.

Because of this flexibility, it was easy to build a custom strategy (`UuidStrategy` in this case) to achieve the desired outcome of obfuscating without a count of record per time-frame.

In light of that, I don't see a benefit to adding a note in README for the lack of secure obfuscation. Do you agree?

**Comment by dereuromark** [comment]
Fair enough. I still think the main plugin use case is not really obfuscating, but shortenting.

**Comment by jadb** [comment]
I agree, it's good for shortening URLs **too** but not limited to just that. 

I personally find that the strength of this plugin is that it can easily accommodate various use cases when it comes to altering the identifier used because of the flexibility strategies bring to the table.

**Comment by dereuromark** [comment]
> flexibility strategies bring to the table

Thats exactly the reason why I think it is not good to be used for this, and why I also had to abandon [Hashid](https://github.com/dereuromark/cakephp-hashid) as even less generic version.
The perceived flexibility makes certain use cases, and especially more complex ones, not possible.

But anyway :) Glad it works for the use cases people need it to.
